export const veg = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    desc: "A rich and creamy dish made with paneer cooked in a tomato-based gravy with butter.",
    price: "20.00",
    image: require("../src/assets/menu/v/pbm.jpg"),
    spicy: false,
  },
  {
    id: 2,
    name: "Aloo Gobi",
    desc: "A classic North Indian dish made with potatoes and cauliflower, flavored with spices.",
    price: "18.00",
    image: require("../src/assets/menu/v/aloo_gobi.jpg"),
    spicy: true,
  },
  {
    id: 3,
    name: "Palak Paneer",
    desc: "Paneer cubes cooked in a smooth spinach gravy, lightly spiced with Indian spices.",
    price: "22.00",
    image: require("../src/assets/menu/v/palak_paneer.jpg"),
    spicy: false,
  },
  {
    id: 4,
    name: "Chole Bhature",
    desc: "A popular Punjabi dish of spiced chickpeas served with deep-fried bread.",
    price: "15.00",
    image: require("../src/assets/menu/v/chole_bhature.jpg"),
    spicy: true,
  },
  {
    id: 5,
    name: "Veg Biryani",
    desc: "A fragrant rice dish cooked with mixed vegetables and aromatic spices.",
    price: "25.00",
    image: require("../src/assets/menu/v/veg_biryani.jpg"),
    spicy: true,
  },
  {
    id: 6,
    name: "Masala Dosa",
    desc: "A crispy South Indian crepe filled with spicy mashed potatoes.",
    price: "12.00",
    image: require("../src/assets/menu/v/masala_dosa.jpg"),
    spicy: true,
  },
  {
    id: 7,
    name: "Malai Kofta",
    desc: "Soft paneer and vegetable dumplings served in a rich and creamy tomato gravy.",
    price: "24.00",
    image: require("../src/assets/menu/v/malai_kofta.jpg"),
    spicy: false,
  },
  {
    id: 8,
    name: "Bhindi Masala",
    desc: "A stir-fried dish of okra cooked with onions, tomatoes, and Indian spices.",
    price: "16.00",
    image: require("../src/assets/menu/v/bhindi_masala.jpg"),
    spicy: true,
  },
  {
    id: 9,
    name: "Kadai Paneer",
    desc: "Paneer cubes cooked in a thick, spiced tomato and bell pepper gravy.",
    price: "23.00",
    image: require("../src/assets/menu/v/kadai_paneer.jpg"),
    spicy: true,
  },
  {
    id: 10,
    name: "Dal Tadka",
    desc: "Yellow lentils cooked with Indian spices and tempered with ghee and garlic.",
    price: "14.00",
    image: require("../src/assets/menu/v/dal_tadka.jpg"),
    spicy: false,
  },
  {
    id: 11,
    name: "Rajma Chawal",
    desc: "Red kidney beans cooked in a spicy gravy served with steamed rice.",
    price: "17.00",
    image: require("../src/assets/menu/v/rajma_chawal.jpg"),
    spicy: true,
  },
  {
    id: 12,
    name: "Mix Veg Curry",
    desc: "A medley of vegetables cooked in a spicy and flavorful curry sauce.",
    price: "20.00",
    image: require("../src/assets/menu/v/mix_veg_curry.jpg"),
    spicy: true,
  },
  {
    id: 13,
    name: "Matar Paneer",
    desc: "Paneer and peas cooked in a mildly spiced tomato and onion gravy.",
    price: "21.00",
    image: require("../src/assets/menu/v/matar_paneer.jpg"),
    spicy: false,
  },
  {
    id: 14,
    name: "Aloo Matar",
    desc: "A comforting dish of potatoes and peas cooked in a spicy gravy.",
    price: "16.00",
    image: require("../src/assets/menu/v/aloo_matar.jpg"),
    spicy: true,
  },
  {
    id: 15,
    name: "Pav Bhaji",
    desc: "A spicy mashed vegetable curry served with buttered bread rolls.",
    price: "18.00",
    image: require("../src/assets/menu/v/pav_bhaji.jpg"),
    spicy: true,
  },
  {
    id: 16,
    name: "Veg Kurma",
    desc: "A South Indian dish of mixed vegetables cooked in a spiced coconut gravy.",
    price: "22.00",
    image: require("../src/assets/menu/v/veg_kurma.jpg"),
    spicy: true,
  },
  {
    id: 17,
    name: "Baingan Bharta",
    desc: "Roasted eggplant mashed and cooked with onions, tomatoes, and spices.",
    price: "19.00",
    image: require("../src/assets/menu/v/baingan_bharta.jpg"),
    spicy: true,
  },
  {
    id: 18,
    name: "Methi Malai Matar",
    desc: "A creamy dish made with fenugreek leaves, peas, and a rich gravy.",
    price: "23.00",
    image: require("../src/assets/menu/v/methi_malai_matar.jpg"),
    spicy: false,
  },
  {
    id: 19,
    name: "Vegetable Pulao",
    desc: "Aromatic basmati rice cooked with mixed vegetables and spices.",
    price: "20.00",
    image: require("../src/assets/menu/v/vegetable_pulao.jpg"),
    spicy: true,
  },
  {
    id: 20,
    name: "Paneer Tikka",
    desc: "Spicy grilled paneer cubes marinated in yogurt and spices.",
    price: "22.00",
    image: require("../src/assets/menu/v/paneer_tikka.jpg"),
    spicy: true,
  },
];

export const nonveg = [
  {
    id: 1,
    name: "Chicken Curry",
    desc: "Aromatic basmati rice cooked with mixed vegetables and spices.",
    price: "20.00",
    image:
      "https://www.pexels.com/photo/indian-chicken-curry-in-gray-ceramic-bowl-5945742/",
    spicy: true,
  },
  {
    id: 2,
    name: "Mutton Rogan Josh",
    desc: "Tender mutton cooked in aromatic spices and yogurt.",
    price: "25.00",
    image:
      "https://www.pexels.com/photo/mutton-rogan-josh-indian-cuisine-5945745/",
    spicy: true,
  },
  {
    id: 3,
    name: "Fish Fry",
    desc: "Crispy fried fish seasoned with Indian spices.",
    price: "18.00",
    image:
      "https://www.pexels.com/photo/fried-fish-on-stainless-steel-grill-1846670/",
    spicy: false,
  },
  {
    id: 4,
    name: "Butter Chicken",
    desc: "Juicy chicken in a creamy tomato sauce.",
    price: "22.00",
    image:
      "https://www.pexels.com/photo/butter-chicken-in-white-ceramic-bowl-5945747/",
    spicy: false,
  },
  {
    id: 5,
    name: "Chicken Biryani",
    desc: "Fragrant basmati rice cooked with chicken and spices.",
    price: "20.00",
    image:
      "https://www.pexels.com/photo/indian-chicken-biryani-served-on-white-plate-5945748/",
    spicy: true,
  },
  {
    id: 6,
    name: "Prawn Masala",
    desc: "Prawns cooked in a rich and spicy tomato-based gravy.",
    price: "23.00",
    image: "https://www.pexels.com/photo/prawn-masala-served-on-bowl-5945749/",
    spicy: true,
  },
  {
    id: 7,
    name: "Lamb Korma",
    desc: "Tender lamb cooked in a creamy sauce with mild spices.",
    price: "26.00",
    image: "https://www.pexels.com/photo/lamb-korma-served-on-plate-5945750/",
    spicy: false,
  },
  {
    id: 8,
    name: "Fish Curry",
    desc: "Spicy fish curry with a blend of tangy and spicy flavors.",
    price: "19.00",
    image: "https://www.pexels.com/photo/fish-curry-served-on-plate-5945751/",
    spicy: true,
  },
  {
    id: 9,
    name: "Tandoori Chicken",
    desc: "Grilled chicken marinated in yogurt and spices.",
    price: "21.00",
    image:
      "https://www.pexels.com/photo/tandoori-chicken-served-on-plate-5945752/",
    spicy: true,
  },
  {
    id: 10,
    name: "Keema Pav",
    desc: "Spiced minced meat served with soft pav bread.",
    price: "17.00",
    image: "https://www.pexels.com/photo/keema-pav-served-on-plate-5945753/",
    spicy: true,
  },
  {
    id: 11,
    name: "Mutton Biryani",
    desc: "Fragrant rice cooked with tender mutton and spices.",
    price: "24.00",
    image:
      "https://www.pexels.com/photo/mutton-biryani-served-on-plate-5945754/",
    spicy: true,
  },
  {
    id: 12,
    name: "Egg Curry",
    desc: "Boiled eggs cooked in a spicy tomato-based gravy.",
    price: "15.00",
    image: "https://www.pexels.com/photo/egg-curry-served-on-plate-5945755/",
    spicy: true,
  },
  {
    id: 13,
    name: "Chicken Tikka",
    desc: "Grilled marinated chicken pieces served with chutney.",
    price: "19.00",
    image:
      "https://www.pexels.com/photo/chicken-tikka-served-on-plate-5945756/",
    spicy: true,
  },
  {
    id: 14,
    name: "Prawn Biryani",
    desc: "Fragrant basmati rice cooked with prawns and spices.",
    price: "23.00",
    image:
      "https://www.pexels.com/photo/prawn-biryani-served-on-plate-5945757/",
    spicy: true,
  },
  {
    id: 15,
    name: "Mutton Korma",
    desc: "Slow-cooked mutton in a rich and creamy sauce.",
    price: "26.00",
    image: "https://www.pexels.com/photo/mutton-korma-served-on-plate-5945758/",
    spicy: false,
  },
  {
    id: 16,
    name: "Chicken 65",
    desc: "Spicy deep-fried chicken pieces seasoned with Indian spices.",
    price: "16.00",
    image: "https://www.pexels.com/photo/chicken-65-served-on-plate-5945759/",
    spicy: true,
  },
  {
    id: 17,
    name: "Mutton Keema",
    desc: "Minced mutton cooked with spices, served with naan.",
    price: "22.00",
    image: "https://www.pexels.com/photo/mutton-keema-served-on-plate-5945760/",
    spicy: true,
  },
  {
    id: 18,
    name: "Chicken Kabab",
    desc: "Grilled chicken skewers with aromatic spices.",
    price: "18.00",
    image:
      "https://www.pexels.com/photo/chicken-kabab-served-on-plate-5945761/",
    spicy: true,
  },
  {
    id: 19,
    name: "Prawn Curry",
    desc: "Prawns cooked in a flavorful curry sauce.",
    price: "23.00",
    image: "https://www.pexels.com/photo/prawn-curry-served-on-plate-5945762/",
    spicy: true,
  },
  {
    id: 20,
    name: "Mutton Stew",
    desc: "Tender mutton pieces cooked in a mild and flavorful broth.",
    price: "25.00",
    image: "https://www.pexels.com/photo/mutton-stew-served-on-plate-5945763/",
    spicy: false,
  },
];



